platform :ios,'8.0'
inhibit_all_warnings!

target "WTDemo" do
    #基础组件
    pod 'WTBaseCore', :git => "https://github.com/jienliang000/WTBaseCore.git"
    pod 'WTPagerController', :git => "https://github.com/jienliang000/WTPagerController.git"
end

